api {
web_server:http://localhost:8080
api_server:http://localhost:8008
files_server:http://localhost:8081
credentials {
"access_key"="LAT6DT6I95SBSANOO2KY4U5CVKLPMJ"
"secret_key"="uLrnDWIAsvsIpeOUKlPq9GnTszer6isLcYBEfdctYHDjz0eE6ZnDsZe4u0uTg4SifJw"
}
}